name: Collect and upload coverage
on: [push, pull_request]
jobs:
  unittest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.9"
      - name: Generate Report
        run: |
          pip install tabulate
          pip install coverage
          coverage run -m unittest
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          verbose: true
