name: Collect and upload coverage
on: [push, pull_request]
jobs:
  unittest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.9"
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.4
      - name: Install dependencies
        run: poetry install
      - name: Generate Report
        run: |
          poetry run pip install coverage
          poetry run coverage run -m unittest
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          verbose: true
